config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'fumans#top'
  get "/index" => "fumans#index"

  resources :fumans do
    resources :likes do
    end
    resources :dislikes do
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dislike.rb
class Dislike < ApplicationRecord
  belongs_to :user
  belongs_to :fuman
end

app/models/fuman.rb
class Fuman < ApplicationRecord
  validates :content, presence: true
  has_many :likes
  has_many :dislikes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :fuman
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes
  has_many :dislikes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dislikes_controller.rb
class DislikesController < ApplicationController
  def create
    @user=User.find_by(id:cookies.signed[:user_id])
    unless Dislike.find_by(user_id:@user.id,fuman_id:params[:fuman_id]).present?
     if Like.find_by(user_id:@user.id,fuman_id:params[:fuman_id]).nil?
      @dislike = Dislike.create(user_id:@user.id,fuman_id:params[:fuman_id])
      @fuman=Fuman.find(params[:fuman_id])
      @fuman.dislike+=1
      @fuman.save
     end
    else
      @dislike = Dislike.find_by(user_id:@user.id,fuman_id:params[:fuman_id])
      @dislike.destroy
      @fuman=Fuman.find(params[:fuman_id])
      @fuman.dislike-=1
      @fuman.save
    end
  redirect_to fumans_path, :method=>:get
  end
end

app/controllers/fumans_controller.rb
class FumansController < ApplicationController
  def sort_by_popularity

  end
  def index
    @user=User.find_by(id:cookies.signed[:user_id])
    @like=Like.find_by(user_id:@user)
    if params[:sort_id].to_i==2
     @fumans = Fuman.where(id:@like.fuman_id).order("created_at DESC")
   elsif params[:sort_id].to_i==1
     @fumans = Fuman.all.order(like: :desc)
    else
     @fumans = Fuman.all.order("created_at DESC")
    end
    @fuman=Fuman.new
  end
  def create
    Fuman.create(content:params[:fuman][:content])
    redirect_to :action => 'index'
  end
  def top
    @fuman = Fuman.new
    @user=User.new
    @user.save
    cookies.signed[:user_id] = { :value => @user.id, :expires => 1.day.from_now }
  end
  def like
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user=User.find_by(id:cookies.signed[:user_id])
    unless Like.find_by(user_id:@user.id,fuman_id:params[:fuman_id]).present?
      if Dislike.find_by(user_id:@user.id,fuman_id:params[:fuman_id]).nil?
        @like = Like.create(user_id:@user.id,fuman_id:params[:fuman_id])
        @fuman=Fuman.find(params[:fuman_id])
        @fuman.like+=1
        @fuman.save
      end
    else
      @like = Like.find_by(user_id:@user.id,fuman_id:params[:fuman_id])
      @like.destroy
      @fuman=Fuman.find(params[:fuman_id])
      @fuman.like-=1
      @fuman.save
    end
  redirect_to fumans_path, :method=>:get
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  has_many :likes
  has_many :dislikes
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dislike_helper.rb
module DislikeHelper
end

app/helpers/fumans_helper.rb
module FumansHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fumans/_Created_Time.html.erb
<%if (Time.current.year)-(fuman.created_at.year)>0%>
  <%= puts (Time.current.year)-(fuman.created_at.year)+"year"%>
<%elsif (Time.current.month)-(fuman.created_at.month)>0%>
  <%= puts (Time.current.month)-(fuman.created_at.month)+"month"%>
<%elsif (Time.current.day)-(fuman.created_at.day)>0%>
  <%= puts (Time.current.day)-(fuman.created_at.day)+"d"%>
<%elsif (Time.current.minutes)-(fuman.created_at.minutes)>0%>
  <%= puts (Time.current.minutes)-(fuman.created_at.minutes)+"m"%>
<%else%>
<%= puts "Just now">

app/views/fumans/_fumans.html.erb
<% @fumans.each do |fuman| %>
<div class="col-md-6 offset-md-3 col-sm-12">
  <div class="fuman shadow1">
    <div class="row fuman_top">
      <div class="col-md-9">
        <div class="row">
          <div class="details">
              <span class="created_ago">
                <%if Time.current.year-fuman.created_at.year>0 %>
                  <%= (Time.current.year-fuman.created_at.year).to_s+"year"%>
                <%elsif Time.current.month-fuman.created_at.month>0 %>
                  <%= (Time.current.month-fuman.created_at.month).to_s+"month"%>
                <%elsif (Time.current.day-fuman.created_at.day)>0%>
                  <%= (Time.current.day-fuman.created_at.day).to_s+"d"%>
                <%elsif (Time.current.min-fuman.created_at.min)>0 %>
                  <%= (Time.current.min-fuman.created_at.min).to_s+"m"%>
                <%else%>
                 <%= "Just now"%>
                <%end%>
              </span>
             <span class="from_name"><%= fuman.name %></span>
             <i class="fas fa-angle-double-right fa-fw"></i><%= fuman.to_whom %>
          </div>
        </div>
      </div>
      <div class=" col-md-3 ">
        <div class="icon">
        <%@user=User.find_by(id:cookies.signed[:user_id])%>
        <%=link_to fuman_likes_path(fuman_id:fuman.id),method:"post" do%>
          <%if Like.find_by(user_id:@user.id,fuman_id:fuman.id).present?%>
           <i class="far fa-thumbs-up fa-fw faa-wrench my-blue animated-hover"></i><span><%=fuman.like%></span>
          <%else%>
           <i class="far fa-thumbs-up fa-fw faa-wrench animated-hover"></i><span><%=fuman.like%></span>
          <%end%>
        <%end%>
        <%=link_to fuman_dislikes_path(fuman_id:fuman.id),method:"post" do%>
          <%if Dislike.find_by(user_id:@user.id,fuman_id:fuman.id).present?%>
            <i class="far fa-thumbs-down fa-fw faa-wrench my-blue animated-hover"></i><span><%=fuman.dislike%></span>
          <%else%>
            <i class="far fa-thumbs-down fa-fw faa-wrench animated-hover"></i><span><%=fuman.dislike%></span>
          <%end%>
        <%end%>
        <i class="fas fa-reply fa-fw faa-bounce animated-hover my-gray fa-lg"></i>
        </div>
       </div>
     </div>
     <div class="row fuman_bottom">
        <i class="fas fa-user-circle"></i>
        <div class="fuman_content col-md-9">
         <%=fuman.content%>
        </div>
     </div>
   </div>
</div>
<% end %>

app/views/fumans/index.html.erb
<div class="jumbotron">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 offset-md-3 col-sm-12 title">
        Wiino
      </div>
    </div>
      <%= form_for(@fuman, url: fumans_path(@fuman), html: {method: "post"}) do |f| %>
      <div class="col-md-6 offset-md-3 input col-sm-12 ">
        <div class="row">
          <%= f.text_field :name,value:"",placeholder:"Annonymous", class:"col-md-3 offset-md-1",id:"name" %>
          <i class="fas fa-angle-double-right fa-2x fa-fw faa-passing my-white animated col-md-2 offset-md-1"></i>
          <%= f.text_field :to_whom, id:"to_whom",class:"col-md-3 offset-md-1",placeholder:"World",value:"" %>
        </div>
      </div>
      <div class="col-md-6 offset-md-3 input col-sm-12">
          <%= f.text_area :content, id:"text",placeholder:"Your wish & request.",value:"" %>
          <div class="row">
           <%= f.submit "Share", class:"btn btn-primary btn-sm col-md-2 offset-md-5",style:"display:hidden;width:100%;background-color:#0278AE;margin-top:10px;" %>
          </div>
      <% end %>
        <div class="row">
          <div class="dropdown offset-md-9 col-md-3">
            <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <%="Sort by"%>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu3">
              <li class="dropdown-header">Sort by</li>
              <li><%=link_to "Latest", index_path(sort_id:0) %></li>
              <li><%=link_to "Popularity", index_path(sort_id:1)%></li>
              <li><%=link_to "Favorite", index_path(sort_id:2)%></li>
            </ul>
            </div>
        </div>
      </div>
      <%= render 'fumans' %>
    </div>
  </div>
</div>

app/views/fumans/top.html.erb
<div class="jumbotron">
  <div class = "container-fluid">
      <div class ="row" >
        <div class="cover-text">
          <h1>Wiino</h1>
        </div>
      </div>
    <%= form_for(@fuman, url: fumans_path(@fuman), html: {method: "post"}) do |f| %>
    <div class ="row" >
      <div class="col-md-6 offset-md-3 input col-sm-12 ">
        <div class="row">
          <%= f.text_field :name,value:"",placeholder:"Annonymous", class:"col-md-3 offset-md-1",id:"name" %>
          <i class="fas fa-angle-double-right fa-2x fa-fw faa-passing  my-white animated col-md-2 offset-md-1"></i>
          <%= f.text_field :to_whom, id:"to_whom",class:"col-md-3 offset-md-1",placeholder:"World",value:"" %>
        </div>
      </div>
      <div class="col-md-6 offset-md-3 input col-sm-12">
          <%= f.text_area :content, id:"text",placeholder:"Your wish & request.",value:"" %>
          <%= f.submit "投稿", class:"btn btn-primary btn-sm",style:"display:hidden;width:100%;background-color:#0278AE;margin-top:10px;" %>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Human</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>